# Generated by Django 5.0.6 on 2024-06-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamento',
            new_name='Patrimonio',
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='equipamento',
            new_name='patrimonio',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='equipamento',
            new_name='patrimonio',
        ),
        migrations.RenameField(
            model_name='saida',
            old_name='equipamento',
            new_name='patrimonio',
        ),
    ]
