# Generated by Django 5.0.6 on 2024-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_patrimonio_tag_patrimonio_rfid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
